baseURL = "https://nicks-homelab.net"
languageCode = "en-us"
title = "Nick von Podewils"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"

    userName = "nick"
    pcName = "deep_thought"
    workDir = "42"
    profile = "profile.txt"

    description = """
    Hi I'm Nick, HA-Linux Admin.
    """
  


    [Params.Tree]
    use = true
    files = [
        ["Blog", "https://nicks-homelab.com/"],
        ["CV", "/works/cv.md"],
        ["GitHub", "https://github.com/HilkopterBob"],
        ["Imprint and legal notice", "https://libraryofbabel.info/"]
    ]
